### ISSUE TITLE
Support for Potion Affixes

### ISSUE THREAD

**Issue by SiverDX** [Daripher/Apothic-Curios#1]
Affix:
https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/java/shadows/apotheosis/adventure/affix/effect/PotionAffix.java

Calls from (might have missed some):

---

Attacking or getting attacked

https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/java/shadows/apotheosis/mixin/EnchantmentHelperMixin.java
(not related to enchanting (the affix logic) - it just uses those points to trigger their logic)

---

Arrow related

First one copies the affixes from the bow to the arrow and on impact it then checks the arrow affixes in the second part
https://github.com/Shadows-of-Fire/Apotheosis/blob/8c41616c3b05e446abb3d718c37f46d963875033/src/main/java/shadows/apotheosis/adventure/AdventureEvents.java#L109-L133
+
https://github.com/Shadows-of-Fire/Apotheosis/blob/8c41616c3b05e446abb3d718c37f46d963875033/src/main/java/shadows/apotheosis/adventure/AdventureEvents.java#L135-L144

---

Block break

https://github.com/Shadows-of-Fire/Apotheosis/blob/8c41616c3b05e446abb3d718c37f46d963875033/src/main/java/shadows/apotheosis/adventure/AdventureEvents.java#L185-L192

---

Blocking

https://github.com/Shadows-of-Fire/Apotheosis/blob/8c41616c3b05e446abb3d718c37f46d963875033/src/main/java/shadows/apotheosis/adventure/AdventureEvents.java#L174-L183

**Comment by Daripher** [comment]
Looks like these don't work with equipment by default, do you think I still should make them work with curios?

**Comment by SiverDX** [comment]
I'm not sure why they shouldn't
It's all configurable anyway and the person doing the configuration is making the decision on which curios to give these affixes

**Comment by SiverDX** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/blob/2157868360b412ec66efc986ac556c6b115afda4/src/main/java/dev/shadowsoffire/apotheosis/adventure/affix/effect/PotionAffix.java#L113-L125

I don't think that one gets triggered yet
Would need

https://github.com/Shadows-of-Fire/Apotheosis/blob/8c41616c3b05e446abb3d718c37f46d963875033/src/main/java/shadows/apotheosis/adventure/AdventureEvents.java#L135-L144

**Comment by Daripher** [comment]
> I don't think that one gets triggered yet

Did you test that?

**Comment by SiverDX** [comment]
Ah wait, right
Apotheosis already handles it

**Comment by Daripher** [comment]
> Ah wait, right Apotheosis already handles it

I think I still forgot one thing
