### ISSUE TITLE
Some mods adding air to item tags, causing errors when getting loot category

### ISSUE THREAD

**Issue by Krimatoria** [Daripher/Apothic-Curios#10]
Hello) There is generally a whole long way of one problem related to several mods. 
Neruina Caught Exception: Apotheosis + SuperBoss + Neruina (Loot Apotheosis Crash Item)

Here is a link to the [original branch](https://github.com/Bawnorton/Neruina/issues/43). Also the Apotheosis [branch](https://github.com/Shadows-of-Fire/Apotheosis/issues/1155)

Please go to the original branch, there are already all screenshots and a description of the problem with detailed file logs and a description of all the interactions of mods that together somehow cause this problem. 

To be very brief. Some item from Apotheosis or as they referred to you, Apothic Curious causes a problem when a creeper explodes in combination with these mods, which causes a crash, but the Neruina mod bypasses this in a single game, but on the server it causes all players to crash. 
That is, it makes it impossible to explode the creepers that "Super Boss" creates in a combination of mods, which causes some kind of item from these mods.

This is just an example of the code, everything else is in the original branches, please take a look)

[Server thread/WARN] [neruina/]: Neruina Caught Exception
6676 | java.lang.RuntimeException: Failed to locate any affixes for air{null} with category LootCategory[curios:back] and rarity LootRarity{common}.
6677 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:71) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6678 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:40) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6679 | at shadows.apotheosis.adventure.loot.AffixConvertLootModifier.doApply(AffixConvertLootModifier.java:37) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]

I found the relationship of the problem and what causes it. The SuperBoss mod that I added to the build where creepers are enhanced with the Enhanced AI mod (their explosion force is greater than usual) strengthens them even more by generating colossal explosions, but this does not cause problems or crashes of the game until the Apotheosis mod is added, it adds its loot to mobs.

![2024-02-08_23 34 16](https://github.com/Daripher/Apothic-Curios/assets/106809386/be7fe216-6dea-47a3-bd3b-c632c6f1f4e9)

**Comment by Daripher** [comment]
Check if any mods (especially made with MCreator) are adding **minecraft:air** into the **curios:back** item tag.

**Comment by Krimatoria** [comment]
> Проверьте, добавляют ли какие-либо моды (особенно созданные с помощью MCreator) **minecraft:air** в тег элемента **curios:back** .

By the way, I just subscribed to your Discord. I'm not good at it, I'm just a player. I am currently trying to test only these mods together.

**Comment by Krimatoria** [comment]
Lightman's Currency - в лог файле есть minecraft:air
Из крипера падают деньги и там есть тег о котором вы говорите. Может это связано?

[08Feb2024 23:03:18.693] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/uncommon/STAT/1.0!

6629 | [08Feb2024 23:03:18.694] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/uncommon/STAT/1.0!

[net.minecraft.world.item.crafting.RecipeManager/]: Parsing error loading recipe teraphobia:blackstone_totem: com.google.gson.JsonSyntaxException: Invalid item: minecraft:air
[net.minecraft.world.item.crafting.RecipeManager/]: Parsing error loading recipe minecraft:ender_eye: com.google.gson.JsonSyntaxException: Invalid item: minecraft:air
[net.minecraft.world.item.crafting.RecipeManager/]: Parsing error loading recipe teraphobia:cursed_head: com.google.gson.JsonSyntaxException: Invalid item: minecraft:air

![image](https://github.com/Daripher/Apothic-Curios/assets/106809386/7d847113-0061-403d-912f-600b702718cc)

**Comment by Daripher** [comment]
Idk, it could be related

**Comment by Krimatoria** [comment]
The GPT chat wrote this about the log file....

![image](https://github.com/Daripher/Apothic-Curios/assets/106809386/fbbc0b74-0240-4f01-816f-12b6923a1b35)

**Comment by Daripher** [comment]
Contact me in discord, it is very hard to communicate here
