### ISSUE TITLE
Attributes apply to non-specified slots (if the item is applicable to multiple slots)

### ISSUE THREAD

**Issue by SiverDX** [Daripher/Apothic-Curios#3]
Tried it and the bonus does get applied
If I lootify a curios item which can only be used on the `trinkets` slot no bonus will be applied (item does not get affixed)

---

![image](https://github.com/Daripher/Apothic-Curios/assets/22003703/bff2f89d-0bab-41d4-947b-23c82c064741)

```json
{
  "type": "apotheosis:attribute",
  "attribute": "minecraft:generic.max_health",
  "operation": "ADDITION",
  "values": {
    "common": {
      "min": 1,
      "steps": 1,
      "step": 1
    },
    "uncommon": {
      "min": 2,
      "steps": 1,
      "step": 1
    },
    "rare": {
      "min": 2,
      "steps": 2,
      "step": 1
    },
    "epic": {
      "min": 3,
      "steps": 2,
      "step": 1
    },
    "mythic": {
      "min": 4,
      "steps": 2,
      "step": 1
    },
    "ancient": {
      "min": 5,
      "steps": 3,
      "step": 1
    }
  },
  "types": [
    "curios:belt",
    "curios:hands",
    "curios:head",
    "curios:ring"
  ]
}
```

---

![image](https://github.com/Daripher/Apothic-Curios/assets/22003703/ca3725b9-2430-4c8d-9a70-8ce6f29fdd56)

![image](https://github.com/Daripher/Apothic-Curios/assets/22003703/4a00c11f-0718-4bd3-885e-7d7bc751426e)

**Comment by Daripher** [comment]
What mods can I use to test this?

**Comment by SiverDX** [comment]
https://www.curseforge.com/minecraft/mc-mods/nameless-trinkets
(One of the examples is from this)

and

https://www.curseforge.com/minecraft/mc-mods/artifacts
(Think this had one with only one slot - the other probably has those too though)
